name: Flatpak Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: flatpak/org.dynodevv.chessboard.json
          bundle: chessboard.flatpak
          upload-artifact: true
